# Generated by Django 3.0.2 on 2020-01-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='image_url',
            field=models.CharField(default='url', max_length=2100),
        ),
    ]
